#!/bin/sh

set -eu

JAR="$1"
OUT="$2"
shift 2

$GRAALVM_HOME/bin/native-image \
      -jar "$JAR" \
      -H:Name="$OUT" \
      --no-server \
      --no-fallback \
      --enable-http \
      --enable-https \
      --enable-all-security-services \
      --initialize-at-build-time \
      --initialize-at-run-time=org.newsclub.net.unix.NativeUnixSocket \
      --allow-incomplete-classpath \
      --report-unsupported-elements-at-runtime \
      -H:EnableURLProtocols=http,https \
      -H:ResourceConfigurationResources=unixsocket/graalvm/resource-config.json,graalvm/resource-config.json \
      -H:ReflectionConfigurationResources=unixsocket/graalvm/reflect-config.json,graalvm/reflect-config.json \
      -H:JNIConfigurationResources=unixsocket/graalvm/jni-config.json \
      -H:+ReportExceptionStackTraces \
      -H:+JNI \
      -J-Dclojure.spec.skip-macros=true \
      -J-Dclojure.compiler.direct-linking=true \
      -J-Xmx3g \
      "$@"
