name: Release

on:
  push:
    branches:
      - "ci/*"
    tags:
      - "v*"

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      graalvm-distribution: ${{ steps.setup.outputs.graalvm-distribution }}
      java-version: ${{ steps.setup.outputs.java-version }}
    steps:
      - name: setup
        id: setup
        run: |
          echo "graalvm-distribution=graalvm-community" >> "$GITHUB_OUTPUT"
          echo "java-version=21" >> "$GITHUB_OUTPUT"

  uberjar:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      # We need to compile using the GraalVM JDK, not the default one. This
      # (hopefully) ensures compatibility, as wel as an explicit choice of
      # Java version.
      #
      - name: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: ${{ needs.configure.outputs.graalvm-distribution }}
          java-version: ${{ needs.configure.outputs.java-version }}

      - uses: actions/checkout@v4
      - name: install-dependencies
        run: lein deps
      - name: Run tests
        run: lein kaocha --reporter documentation
      - name: build-uberjar
        run: lein uberjar && mv target/*-standalone.jar target/app.jar
      - name: upload-uberjar
        uses: actions/upload-artifact@v1
        with:
          name: uberjar
          path: target/app.jar
      - name: build-standalone-jar
        run: |
          echo '#!/bin/sh' > into.jar
          echo 'SELF=`which "$0" 2>/dev/null`' >> into.jar
          echo '[ $? -gt 0 -a -f "$0" ] && SELF="./$0"' >> into.jar
          echo 'exec java -jar "$SELF" "$@"' >> into.jar
          echo 'exit 1' >> into.jar
          cat target/app.jar >> into.jar
          chmod +x into.jar
      - name: upload-standalone-jar
        uses: actions/upload-artifact@v1
        with:
          name: standalone-jar
          path: into.jar

  create-native-image:
    strategy:
      matrix:
        build:
          - "linux-amd64"
          - "linux-amd64-static"
          - "macos-amd64"
          - "windows-amd64"
        include:
          - build: "linux-amd64"
            os: "ubuntu-latest"
            flags: ""
          - build: "linux-amd64-static"
            os: "ubuntu-latest"
            flags: "--static"
          - build: "macos-amd64"
            os: "macos-latest"
            flags: ""
          - build: "windows-amd64"
            os: "windows-latest"
            flags: ""
    needs: [uberjar, configure]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: ${{ needs.configure.outputs.graalvm-distribution }}
          java-version: ${{ needs.configure.outputs.java-version }}

      - name: setup-tool-paths
        id: paths
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "NATIVE_IMAGE=native-image.cmd" >> "$GITHUB_ENV"
            echo "ARTIFACT_NAME=into.exe" >> "$GITHUB_ENV"
          else
            echo "NATIVE_IMAGE=native-image" >> "$GITHUB_ENV"
            echo "ARTIFACT_NAME=into" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: setup-windows-toolchain
        uses: ilammy/msvc-dev-cmd@v1
        if: startsWith(matrix.build, 'windows-')
      - name: download-uberjar
        uses: actions/download-artifact@v1
        with:
          name: uberjar
      - name: native-image
        run: |
          ${{ env.NATIVE_IMAGE }} -jar uberjar/app.jar \
            -o into \
            -march=compatibility \
            --no-fallback \
            ${{ matrix.flags }}
        shell: bash
      - name: verify-native-image
        run: |
          export ARTIFACT="${{ github.workspace }}/${{ env.ARTIFACT_NAME }}"
          chmod +x "$ARTIFACT"
          "$ARTIFACT" --version
        shell: bash
      - name: upload-native-image
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.build }}
          path: ${{ env.ARTIFACT_NAME }}

  test-native-image:
    needs: [create-native-image]
    strategy:
      matrix:
        build:
          # We cannot run the actual e2e test for all binaries here since the
          # Windows runner is not configured to be able to use Linux images, and
          # the MacOS runner does not even have Docker. Once that changes, we can
          # merge this whole job with the one above.
          - "linux-amd64"
          - "linux-amd64-static"
        include:
          - build: "linux-amd64"
            os: "ubuntu-latest"
          - build: "linux-amd64-static"
            os: "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: download-native-image
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.build }}
      - name: run-e2e-test
        run: |
          export ARTIFACT="${{ github.workspace }}/${{ matrix.build }}/into"
          chmod +x "$ARTIFACT"
          sh test/e2e/test.sh "$GITHUB_SHA" "$ARTIFACT build"
        env:
          DOCKER_API_VERSION: "1.40"

  create-release:
    needs: [test-native-image]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    outputs:
      upload-url: ${{ steps.create-release.outputs.upload_url }}
      version: ${{ steps.export-version.outputs.version }}
    steps:
      - name: export-version
        id: export-version
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"
      - name: create-release
        id: create-release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ steps.export-version.outputs.version }}
          body: |
            Version ${{ steps.export-version.outputs.version }}
          draft: true
          prerelease: false

  upload-native-release-artifact:
    strategy:
      matrix:
        build:
          [
            "linux-amd64",
            "linux-amd64-static",
            "macos-amd64",
            "windows-amd64",
            "standalone-jar",
          ]
    needs: [create-release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: download-native-image
        uses: actions/download-artifact@v1
        with:
          name: ${{ matrix.build }}
      - name: zip-native-image
        run: cd ${{ matrix.build }} && zip into.zip *
      - name: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload-url }}
          asset_path: ./${{ matrix.build }}/into.zip
          asset_name: into-${{ needs.create-release.outputs.version }}-${{ matrix.build }}.zip
          asset_content_type: application/zip
